feat(cart items): add support for cart items pass through [TA-458]
gr4vy/gr4vy-embed pull request #51
Opened 2022-01-04 14:45 UTC by gryevns

Adds support for passing an array of cart items via embed.

2022-01-10 09:23 UTC, douglaseggleton commented on packages/embed/src/validation.ts
> +  validateType({
I don't think we need to be super strict at the moment - as long as its an array of data, the API will return an error.

2022-01-10 09:24 UTC, douglaseggleton commented on packages/embed/src/types.ts
> +  cartItems?: Array<Record<string, unknown>>
I think the interface is important for library consumers - https://github.com/gr4vy/embed-ui/pull/142/files
Embed UI doesn't need to know - but end users using TS will benefit from it.

2022-01-10 09:26 UTC, douglaseggleton requested changes
LGTM - I think just needs the typings.

2022-01-10 10:26 UTC, douglaseggleton approved these changes

2022-01-11 12:49 UTC, merged

2022-01-11 14:54 UTC, gr4vy-code commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v2.6.0`](https://github.com/gr4vy/gr4vy-embed/releases/tag/v2.6.0) :rocket: