feat(statement descriptor): pass through statement descriptor object [TA-564]
gr4vy/gr4vy-embed pull request #52
Opened 2022-01-04 14:54 UTC by gryevns

Support the pass through of statement descriptor config from embed.

2022-01-10 09:27 UTC, douglaseggleton requested changes

2022-01-10 09:27 UTC, douglaseggleton commented on packages/embed/src/types.ts
> +  statementDescriptor?: Record<string, string>
The typings are important in this library - but not Embed UI

2022-01-10 10:27 UTC, douglaseggleton submitted a review, later dismissed

2022-01-18 09:51 UTC, douglaseggleton approved these changes

2022-01-18 09:57 UTC, merged

2022-01-18 10:00 UTC, gr4vy-code commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v2.7.0`](https://github.com/gr4vy/gr4vy-embed/releases/tag/v2.7.0) :rocket: